# Generated by Django 5.0.14 on 2026-03-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restore', '0007_seed_nudges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nudge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usernudge',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time_zone',
            new_name='timezone',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='userbaselinesurveysectionresponse',
            name='baseline_survey_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_survey_section_responses', to='restore.baselinesurveysection'),
        ),
        migrations.AlterField(
            model_name='userbaselinesurveysectionresponse',
            name='user_baseline_survey_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_baseline_survey_responses', to='restore.userbaselinesurveydetail'),
        ),
        migrations.AlterField(
            model_name='usernudge',
            name='nudge_response',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usernudge',
            name='responded_at',
            field=models.DateTimeField(),
        ),
    ]
