# Generated by Django 5.0.14 on 2026-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0010_seed_energy_plan_suggestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energyplansuggestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userenergyplansuggestion',
            options={},
        ),
        migrations.AlterField(
            model_name='userenergyplansuggestion',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userenergyplansuggestion',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
