# Generated by Django 5.0.14 on 2026-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0011_alter_energyplansuggestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy_schedule_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
