# Generated by Django 5.0.14 on 2026-04-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0012_user_energy_schedule_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronotype', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('time_num', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'energy_schedules',
            },
        ),
    ]
