# Generated by Django 5.0.14 on 2026-04-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0014_seed_energy_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy_schedule_message_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
