# Generated by Django 5.0.14 on 2026-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0019_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
