# Generated by Django 5.0.14 on 2026-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restore', '0024_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
